#!/usr/bin/env ruby
# -*- coding: iso-8859-1 -*-

require 'fileutils'
version = File.new('version.txt').read

note = %Q<
/*
   _   _  ___ ___  _ ____   __
  | | | |/ __/ _ \\| '_ \\ \\ / /  C++ Physical magnitudes and units conversion
  | |_| | (_| (_) | | | \\ V /   Version #{version.chomp}
   \\__,_|\\___\\___/|_| |_|\\_/    https://github.com/lrleon/uconv

  This file is part of uconv library

  Copyright (c) 2018     Ixhel Mejias
                         Alberto Valderrama
                         Fernando Montilla
                         Eduardo Valderrama
                         Neylith Quintero
                         Felix Buccellato
                         Virginia Buccellato
                         Leandro Rabindranath Leon

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
>

file_name = ARGV.shift
file = File.new(file_name).read

puts note, file
